"""
ZettaBrain RAG — FastAPI Web Server (HTTPS)
Serves the GUI over TLS using the certificate generated by setup.sh.
"""

import asyncio
import json
import os
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Optional

import requests
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from .retrieval import hybrid_retrieve, RAG_PROMPT, format_context

# -------------------------------------------------------
# Paths
# -------------------------------------------------------
PKG_DIR    = Path(__file__).parent
STATIC_DIR = PKG_DIR / "static"

if os.name == "nt":
    _local_app = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
    DEPLOY_DIR = _local_app / "ZettaBrain"
    CERT_DIR   = _local_app / "ZettaBrain" / "certs"
else:
    DEPLOY_DIR = Path("/opt/zettabrain/src")
    CERT_DIR   = Path("/opt/zettabrain/certs")
CHROMA_PATH  = DEPLOY_DIR / "zettabrain_vectorstore"
INGEST_LOG   = DEPLOY_DIR / "ingested_files.json"
CONFIG_FILE  = DEPLOY_DIR / "zettabrain.env"
STORAGE_CONF = DEPLOY_DIR / "storage.conf"

# -------------------------------------------------------
# Load config from zettabrain.env
# -------------------------------------------------------
def _load_config() -> dict:
    cfg = {}
    if CONFIG_FILE.exists():
        for line in CONFIG_FILE.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                cfg[k.strip()] = v.strip().strip('"')
    return cfg

_cfg = _load_config()

OLLAMA_URL   = os.environ.get("OLLAMA_HOST")           or _cfg.get("OLLAMA_HOST")           or "http://localhost:11434"
LLM_MODEL    = os.environ.get("ZETTABRAIN_LLM_MODEL")  or _cfg.get("ZETTABRAIN_LLM_MODEL")  or "llama3.1:8b"
EMBED_MODEL  = os.environ.get("ZETTABRAIN_EMBED_MODEL") or _cfg.get("ZETTABRAIN_EMBED_MODEL") or "nomic-embed-text"
DOCS_FOLDER  = os.environ.get("ZETTABRAIN_DOCS")        or _cfg.get("RAG_DATA_PATH")         or "/opt/zettabrain/data"
STORAGE_TYPE = _cfg.get("STORAGE_TYPE",            "local")
CERT_FILE    = _cfg.get("ZETTABRAIN_CERT",         str(CERT_DIR / "cert.pem"))
KEY_FILE     = _cfg.get("ZETTABRAIN_KEY",          str(CERT_DIR / "key.pem"))
FINGERPRINT  = _cfg.get("ZETTABRAIN_TLS_FINGERPRINT", "")

# -------------------------------------------------------
# Vectorstore cache — one instance shared across all requests
# -------------------------------------------------------
_vs_lock     = threading.Lock()
_vs_cache: dict = {"vs": None}

def _get_vs():
    """Return the cached Chroma instance, initialising on first call."""
    with _vs_lock:
        if _vs_cache["vs"] is None:
            from langchain_ollama import OllamaEmbeddings
            from langchain_chroma import Chroma
            emb = OllamaEmbeddings(model=EMBED_MODEL, base_url=OLLAMA_URL)
            _vs_cache["vs"] = Chroma(
                persist_directory=str(CHROMA_PATH),
                embedding_function=emb,
                collection_name="zettabrain_docs",
            )
        return _vs_cache["vs"]

def _reset_vs_cache():
    with _vs_lock:
        _vs_cache["vs"] = None


# -------------------------------------------------------
# GPU detection
# -------------------------------------------------------
def _get_gpu_info() -> dict:
    info = {"type": "none", "name": None, "vram_gb": 0, "recommended_model": None}
    # NVIDIA
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=name,memory.total",
             "--format=csv,noheader,nounits"],
            stderr=subprocess.DEVNULL, timeout=5
        ).decode().strip().splitlines()[0]
        name, vram_mb = [s.strip() for s in out.split(",")]
        vram_gb = int(vram_mb) // 1024
        info.update({"type": "nvidia", "name": name, "vram_gb": vram_gb})
    except Exception:
        pass

    # AMD (ROCm)
    if info["type"] == "none":
        try:
            out = subprocess.check_output(
                ["rocm-smi", "--showmeminfo", "vram"], stderr=subprocess.DEVNULL, timeout=5
            ).decode()
            import re
            m = re.search(r"(\d+)\s*MB", out)
            if m:
                info.update({"type": "amd", "vram_gb": int(m.group(1)) // 1024})
        except Exception:
            pass

    # Apple Silicon (Metal — unified memory)
    if info["type"] == "none":
        try:
            if subprocess.check_output(["uname", "-m"]).decode().strip() == "arm64":
                mem = int(subprocess.check_output(
                    ["sysctl", "-n", "hw.memsize"]).decode().strip())
                info.update({"type": "apple_silicon", "vram_gb": mem // 1_073_741_824})
        except Exception:
            pass

    # Recommend model based on available VRAM
    vg = info["vram_gb"]
    if info["type"] == "none" or vg == 0:
        info["recommended_model"] = "phi4:3.8b"
    elif vg >= 24:
        info["recommended_model"] = "qwen2.5:32b"
    elif vg >= 16:
        info["recommended_model"] = "qwen2.5:14b"
    elif vg >= 12:
        info["recommended_model"] = "mistral-nemo:12b"
    elif vg >= 8:
        info["recommended_model"] = "llama3.1:8b"
    elif vg >= 5:
        info["recommended_model"] = "mistral:7b"
    else:
        info["recommended_model"] = "phi4:3.8b"

    return info


# -------------------------------------------------------
# App
# -------------------------------------------------------
app = FastAPI(title="ZettaBrain RAG", version="0.2.0")


@app.on_event("startup")
async def _warmup():
    """Pre-load the vectorstore and FlashRank so the first query isn't slow."""
    if not CHROMA_PATH.exists():
        return
    try:
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, _get_vs)
    except Exception:
        pass

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


# -------------------------------------------------------
# Models
# -------------------------------------------------------
class ChatRequest(BaseModel):
    question: str
    model: Optional[str] = None

class IngestRequest(BaseModel):
    folder: Optional[str] = None
    rebuild: bool = False

class SettingsRequest(BaseModel):
    llm_model: Optional[str] = None
    docs_folder: Optional[str] = None

class PullRequest(BaseModel):
    model: str


# -------------------------------------------------------
# Helpers
# -------------------------------------------------------
def _get_python() -> str:
    if os.name == "nt":
        local_app = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        home      = Path.home()
        venv_scripts = [
            local_app / "pipx" / "venvs" / "zettabrain-rag" / "Scripts",
            home / ".local" / "pipx" / "venvs" / "zettabrain-rag" / "Scripts",
        ]
        candidates = [Path(sys.executable)] + [
            p for d in venv_scripts for p in d.glob("python*.exe") if p.exists()
        ]
    else:
        candidates = [
            *list(Path("/root/.local/share/pipx/venvs/zettabrain-rag").rglob("python3")),
            *list(Path("/opt/zettabrain/venv/bin").glob("python3")),
            Path(sys.executable),
        ]
    for c in candidates:
        if Path(c).exists():
            r = subprocess.run([str(c), "-c", "import langchain_community"],
                               capture_output=True)
            if r.returncode == 0:
                return str(c)
    return sys.executable

def _ollama_running() -> bool:
    """Check Ollama is reachable — always use http:// internally."""
    _url = OLLAMA_URL.replace("https://", "http://")  # Ollama API is never TLS
    try:
        r = requests.get(_url, timeout=5)
        return r.status_code == 200
    except requests.exceptions.ConnectionError:
        return False
    except Exception:
        return False

def _get_chunk_count() -> int:
    try:
        import chromadb
        client = chromadb.PersistentClient(path=str(CHROMA_PATH))
        return client.get_collection("zettabrain_docs").count()
    except Exception:
        return 0

def _get_sources() -> list:
    if not INGEST_LOG.exists():
        return []
    try:
        data = json.loads(INGEST_LOG.read_text(encoding="utf-8"))
        return sorted([Path(p).name for p in data.keys()])
    except Exception:
        return []

def _get_ollama_models() -> list:
    try:
        r = requests.get(f"{OLLAMA_URL}/api/tags", timeout=5)
        if r.status_code == 200:
            return [m["name"] for m in r.json().get("models", [])]
    except Exception:
        pass
    return []

def _get_tls_info() -> dict:
    cert = Path(CERT_FILE)
    return {
        "enabled":     cert.exists(),
        "cert_file":   CERT_FILE,
        "fingerprint": FINGERPRINT,
    }

def _get_storage_sources() -> list[dict]:
    """Return all configured storage sources from storage.conf."""
    sources = []
    if STORAGE_CONF.exists():
        for line in STORAGE_CONF.read_text(encoding="utf-8").splitlines():
            if line.startswith("#") or not line.strip():
                continue
            parts = line.split("|")
            if len(parts) >= 4:
                sources.append({
                    "role":  parts[0].strip(),
                    "type":  parts[1].strip(),
                    "label": parts[2].strip(),
                    "path":  parts[3].strip(),
                })
    # Fall back to primary DOCS_FOLDER if no conf file
    if not sources:
        sources.append({"role": "primary", "type": STORAGE_TYPE,
                        "label": DOCS_FOLDER, "path": DOCS_FOLDER})
    return sources

def _count_docs_all_sources() -> int:
    """Count supported documents across every configured storage path."""
    total = 0
    seen  = set()
    for src in _get_storage_sources():
        p = Path(src["path"])
        if p in seen or not p.exists():
            continue
        seen.add(p)
        for ext in ["*.pdf", "*.txt", "*.docx", "*.md"]:
            total += len(list(p.rglob(ext)))
    return total


# -------------------------------------------------------
# Routes
# -------------------------------------------------------
@app.get("/", response_class=HTMLResponse)
async def root():
    index = STATIC_DIR / "index.html"
    if index.exists():
        return HTMLResponse(index.read_text(encoding="utf-8"))
    return HTMLResponse("<h1>ZettaBrain</h1><p>Static files not found.</p>")


@app.get("/api/status")
async def status():
    chunks          = _get_chunk_count()
    ingested        = _get_sources()
    models          = _get_ollama_models()
    storage_sources = _get_storage_sources()
    doc_count       = _count_docs_all_sources()

    return {
        "ollama": {
            "running":      _ollama_running(),
            "url":          OLLAMA_URL,
            "models":       models,
            "active_llm":   LLM_MODEL,
            "active_embed": EMBED_MODEL,
        },
        "vectorstore": {
            "exists": CHROMA_PATH.exists(),
            "chunks": chunks,
            "path":   str(CHROMA_PATH),
        },
        "storage": {
            "type":        STORAGE_TYPE,
            "path":        DOCS_FOLDER,
            "doc_count":   doc_count,
            "configured":  any(Path(s["path"]).exists() for s in storage_sources),
            "sources":     storage_sources,
        },
        "hardware": _get_gpu_info(),
        "tls":      _get_tls_info(),
        "sources":  ingested,
    }


@app.get("/api/models")
async def get_models():
    return {"models": _get_ollama_models()}


@app.get("/api/sources")
async def get_sources():
    return {"sources": _get_sources()}


@app.post("/api/settings")
async def save_settings(req: SettingsRequest):
    global LLM_MODEL, DOCS_FOLDER
    updated = {}

    if req.llm_model:
        LLM_MODEL = req.llm_model
        updated["llm_model"] = LLM_MODEL
    if req.docs_folder:
        DOCS_FOLDER = req.docs_folder
        updated["docs_folder"] = DOCS_FOLDER

    try:
        CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
        cfg: dict[str, str] = {}
        if CONFIG_FILE.exists():
            for line in CONFIG_FILE.read_text(encoding="utf-8").splitlines():
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    cfg[k.strip()] = v.strip().strip('"')
        if req.llm_model:
            cfg["ZETTABRAIN_LLM_MODEL"] = req.llm_model
        if req.docs_folder:
            cfg["RAG_DATA_PATH"] = req.docs_folder
        CONFIG_FILE.write_text(
            "\n".join(f'{k}="{v}"' for k, v in cfg.items()) + "\n",
            encoding="utf-8",
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save config: {e}")

    return {"success": True, "updated": updated}


@app.post("/api/pull")
async def pull_model(req: PullRequest):
    """Stream ollama pull progress back to the client as plain text."""
    queue: asyncio.Queue = asyncio.Queue()
    loop = asyncio.get_event_loop()

    def _do_pull():
        try:
            resp = requests.post(
                f"{OLLAMA_URL}/api/pull",
                json={"name": req.model, "stream": True},
                stream=True,
                timeout=600,
            )
            if resp.status_code != 200:
                asyncio.run_coroutine_threadsafe(
                    queue.put(f"Error: Ollama returned {resp.status_code}\n"), loop
                )
                return
            for line in resp.iter_lines():
                if not line:
                    continue
                try:
                    chunk = json.loads(line)
                    status_msg = chunk.get("status", "")
                    if chunk.get("total") and chunk.get("completed") is not None:
                        pct = int(chunk["completed"] / chunk["total"] * 100)
                        msg = f"{status_msg} {pct}%\n"
                    elif status_msg:
                        msg = f"{status_msg}\n"
                    else:
                        continue
                    asyncio.run_coroutine_threadsafe(queue.put(msg), loop)
                except Exception:
                    pass
        except Exception as exc:
            asyncio.run_coroutine_threadsafe(queue.put(f"Error: {exc}\n"), loop)
        finally:
            asyncio.run_coroutine_threadsafe(queue.put(None), loop)

    loop.run_in_executor(None, _do_pull)

    async def _gen():
        while True:
            msg = await queue.get()
            if msg is None:
                break
            yield msg

    return StreamingResponse(_gen(), media_type="text/plain")


@app.post("/api/ingest")
async def ingest(req: IngestRequest):
    python = _get_python()

    # Prefer a deployed copy; fall back to the script bundled inside the package.
    script = DEPLOY_DIR / "05_ingest_documents.py"
    if not script.exists():
        script = PKG_DIR / "scripts" / "05_ingest_documents.py"
    if not script.exists():
        raise HTTPException(status_code=404, detail="Ingest script not found.")

    # Ensure working dir exists so ingested_files.json lands in the right place.
    DEPLOY_DIR.mkdir(parents=True, exist_ok=True)

    cmd = [python, str(script)]
    if req.folder:  cmd += ["--folder", req.folder]
    if req.rebuild: cmd += ["--rebuild"]

    # Inject paths as env vars so the script uses the correct platform paths
    # instead of its own hardcoded Linux defaults.
    env = os.environ.copy()
    env["ZETTABRAIN_CHROMA"] = str(CHROMA_PATH)
    env["ZETTABRAIN_DOCS"]   = req.folder or DOCS_FOLDER
    env["OLLAMA_HOST"]       = OLLAMA_URL

    try:
        result = subprocess.run(
            cmd, cwd=str(DEPLOY_DIR),
            capture_output=True, text=True, timeout=600, env=env,
        )
        if result.returncode == 0:
            _reset_vs_cache()
        return {
            "success": result.returncode == 0,
            "output":  result.stdout,
            "error":   result.stderr if result.returncode != 0 else None,
            "chunks":  _get_chunk_count(),
        }
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=408, detail="Ingestion timed out.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/chat")
async def chat(req: ChatRequest):
    if not _ollama_running():
        raise HTTPException(status_code=503, detail="Ollama is not running.")
    if _get_chunk_count() == 0:
        raise HTTPException(status_code=422, detail="Vector store is empty. Run ingestion first.")

    model = req.model or LLM_MODEL
    question = req.question

    def _run():
        from langchain_ollama import OllamaLLM
        from langchain_core.prompts import PromptTemplate
        from langchain_core.output_parsers import StrOutputParser

        vs      = _get_vs()
        t0      = time.monotonic()
        sources = hybrid_retrieve(question, vs)
        t_retr  = time.monotonic() - t0

        context = format_context(sources)
        prompt  = PromptTemplate.from_template(RAG_PROMPT)
        llm     = OllamaLLM(model=model, base_url=OLLAMA_URL,
                             temperature=0.0, num_predict=1024)
        t1      = time.monotonic()
        answer  = (prompt | llm | StrOutputParser()).invoke(
                      {"context": context, "question": question}
                  )
        t_gen   = time.monotonic() - t1
        return sources, answer, t_retr, t_gen

    try:
        loop = asyncio.get_event_loop()
        sources, answer, t_retr, t_gen = await loop.run_in_executor(None, _run)

        return {
            "answer":          answer,
            "model":           model,
            "chunks_searched": len(sources),
            "timing": {
                "retrieve_ms": round(t_retr * 1000),
                "generate_ms": round(t_gen  * 1000),
            },
            "sources": [
                {"filename": Path(s.metadata.get("source", "?")).name,
                 "page":     s.metadata.get("page", ""),
                 "preview":  s.page_content[:200]}
                for s in sources
            ],
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.websocket("/ws/chat")
async def websocket_chat(websocket: WebSocket):
    await websocket.accept()
    try:
        while True:
            data     = await websocket.receive_text()
            payload  = json.loads(data)
            question = payload.get("question", "").strip()
            model    = payload.get("model", LLM_MODEL)

            if not question:
                await websocket.send_json({"type": "error", "message": "Empty question"})
                continue
            if not _ollama_running():
                await websocket.send_json({"type": "error", "message": "Ollama is not running"})
                continue
            if _get_chunk_count() == 0:
                await websocket.send_json({"type": "error", "message": "Vector store is empty"})
                continue

            try:
                loop = asyncio.get_event_loop()
                vectorstore = await loop.run_in_executor(None, _get_vs)

                t_r0    = time.monotonic()
                sources = await loop.run_in_executor(
                    None, lambda: hybrid_retrieve(question, vectorstore)
                )
                t_retr  = time.monotonic() - t_r0
                source_list = [
                    {"filename": Path(s.metadata.get("source", "?")).name,
                     "page":     s.metadata.get("page", ""),
                     "preview":  s.page_content[:200]}
                    for s in sources
                ]
                await websocket.send_json({"type": "sources", "sources": source_list})

                context     = format_context(sources)
                prompt_text = RAG_PROMPT.format(context=context, question=question)

                queue: asyncio.Queue = asyncio.Queue()
                t_g0 = time.monotonic()

                def _stream_ollama():
                    try:
                        resp = requests.post(
                            f"{OLLAMA_URL}/api/generate",
                            json={"model": model, "prompt": prompt_text, "stream": True},
                            stream=True, timeout=600,
                        )
                        if resp.status_code != 200:
                            asyncio.run_coroutine_threadsafe(
                                queue.put(("error", f"Ollama {resp.status_code}: {resp.text[:300]}")), loop
                            )
                            return
                        for line in resp.iter_lines():
                            if line:
                                chunk = json.loads(line)
                                if "error" in chunk:
                                    asyncio.run_coroutine_threadsafe(
                                        queue.put(("error", f"Ollama: {chunk['error']}")), loop
                                    )
                                    return
                                token = chunk.get("response", "")
                                asyncio.run_coroutine_threadsafe(
                                    queue.put(("token", token)), loop
                                )
                                if chunk.get("done"):
                                    break
                    except Exception as exc:
                        asyncio.run_coroutine_threadsafe(
                            queue.put(("error", str(exc))), loop
                        )
                    finally:
                        asyncio.run_coroutine_threadsafe(
                            queue.put(("done", None)), loop
                        )

                loop.run_in_executor(None, _stream_ollama)

                full_answer = ""
                error_msg   = None
                while True:
                    kind, value = await queue.get()
                    if kind == "token":
                        full_answer += value
                        await websocket.send_json({"type": "token", "token": value})
                    elif kind == "error":
                        error_msg = value
                        break
                    else:  # "done"
                        break

                if error_msg:
                    await websocket.send_json({"type": "error", "message": error_msg})
                    continue

                if not full_answer.strip():
                    await websocket.send_json({
                        "type":    "error",
                        "message": f"Ollama returned an empty response. "
                                   f"Check that '{model}' is pulled: ollama pull {model}",
                    })
                    continue

                t_gen = time.monotonic() - t_g0
                await websocket.send_json({
                    "type":            "done",
                    "answer":          full_answer,
                    "model":           model,
                    "chunks_searched": len(sources),
                    "timing": {
                        "retrieve_ms": round(t_retr * 1000),
                        "generate_ms": round(t_gen  * 1000),
                    },
                })

            except Exception as e:
                msg = str(e)
                if "hnsw" in msg.lower() or "segment" in msg.lower() or "nothing found on disk" in msg.lower():
                    _reset_vs_cache()
                    msg = (
                        "The vector store index is corrupt (partial ingest). "
                        "Click '🗑 Clear Vector Store' in the sidebar, then re-run ingestion."
                    )
                await websocket.send_json({"type": "error", "message": msg})

    except WebSocketDisconnect:
        pass


@app.delete("/api/vectorstore")
async def clear_vectorstore():
    _reset_vs_cache()
    errors = []

    # Try the clean ChromaDB API path first
    try:
        import chromadb
        chromadb.PersistentClient(path=str(CHROMA_PATH)).delete_collection("zettabrain_docs")
    except Exception as e:
        errors.append(f"chromadb delete: {e}")
        # If ChromaDB itself is corrupt (e.g. "hnsw segment reader: Nothing found on disk"),
        # wipe the directory so the next ingest starts fresh.
        if CHROMA_PATH.exists():
            try:
                shutil.rmtree(str(CHROMA_PATH))
            except Exception as e2:
                errors.append(f"rmtree: {e2}")
                raise HTTPException(status_code=500, detail="; ".join(errors))

    # Reset the ingest tracking log
    if INGEST_LOG.exists():
        INGEST_LOG.write_text("{}", encoding="utf-8")

    msg = "Vector store cleared."
    if errors:
        msg += " (recovered via filesystem wipe — was corrupt)"
    return {"success": True, "message": msg}
